version: "2"
services: 
  web:
    build:
    container_name: web_service
    ports:
      - 8000:80
    volumes: 
      - ./html:/var/www/html/
    links:
      - "db"
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234    
